### ISSUE TITLE
i need yuv pixelbuffer input

### ISSUE THREAD

**Issue by chenchangqing** [YuAo/YUGPUImageCVPixelBufferInput#2]

**Comment by YuAo** [comment]
This library is deprecated and no longer maintained.

The YUV input support can be implemented by creating two CVOpenGLTextureRef, one for the Y channel and one for the UV channel. Then you need to create a filter that takes two inputs (Y and UV channel image) and converts them to a RGB texture.

A "Metal" based implementation can be found at https://github.com/MetalPetal/MetalPetal/blob/master/Frameworks/MetalPetal/MTICVPixelBufferPromise.m#L261
